### ISSUE TITLE
Index out of range on aarch64

### ISSUE THREAD

**Issue by bertronika** [the-maldridge/PopCorn#2]
Following error appears when manually launching popcorn either with sudo or without.
```
$ popcorn -server popcorn.voidlinux.org -port 8001
panic: runtime error: index out of range

goroutine 1 [running]:
main.getXUname(0x4000222200)
	/builddir/PopCorn-0.4/cmd/popcorn/main.go:96 +0x430
main.main()
	/builddir/PopCorn-0.4/cmd/popcorn/main.go:152 +0x4d0
```
System:
- xuname:
`Void 4.19.68_1 aarch64  uptodate rFF`
- package:
`PopCorn-0.4_1`

**Comment by Johnnynator** [comment]
Can you post your xuname output?

**Comment by bertronika** [comment]
`Void 4.19.68_1 aarch64 uptodate rFF`, as stated.

**Comment by Johnnynator** [comment]
Mh..., Sorry. Seems like I can't read that early in the morning :D.

This issue is that xuname not always prints the CPU vendor/platform. This should be resolved once https://github.com/leahneukirchen/xtools/pull/153 is merged and a new version of xtools is in the repo

**Comment by the-maldridge** [comment]
linked issue was merged.  Having not heard back here I can only assume this is resolved.  If not we'll reopen this issue.
