### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [the-maldridge/PopCorn#3]
I was playing around with this dataset
Is there any aggregated data for `xbps-query` search queries and also queries from https://voidlinux.org/packages/ It could be used for proactively releasing packages for searches with high 404's.

**Comment by the-maldridge** [comment]
No.  xbps-query works by parsing the repodata file, so all searching is done locally.  Similarly for /packages/ it parses the index data, not the repo itself, so there are no 404's.

**Comment by ghost** [comment]
Interesting. I just checked - /packages/ It is hitting the API https://xq-api.voidlinux.org/v1/query/x86_64?q=go1.12 Could probably add a logger for queries with empty results in the backend.

**Comment by the-maldridge** [comment]
You might be interested in looking at xq-api directly then.  https://github.com/Nilium/xq-api.

A long term goal from a while ago was to have an actual packages site.  With nice stuff where you could search for a package, and get all the data that's in the index as well as get the information that's in popcorn.  If you're interested in working on that project feel free to join in #xbps on freenode to discuss it.

**Comment by anaggh** [comment]
It's starting to take shape.

Demo: http://void.citta.in/

Source: https://github.com/anaggh/void-packages-web

**Comment by anaggh** [comment]
Btw, is there any IRC logs for #xbps and #voidlinux like https://dev.alpinelinux.org/irclogs/ or https://irclogs.ubuntu.com/  ?
